Repository TOPLLab/WARDuino, pull requests merged in 2024-12, with the labels that each got.

#284 ⬆️ Bump latch to 0.3.1
  tests/latch/latch-0.3.0.tgz
  tests/latch/latch-0.3.1.tgz
  tests/latch/package.json
Labels: dependencies

#286 🎨 Add `--version` option to wdcli
  platforms/CLI-Emulator/main.cpp
Labels: feature

#287 👷 Add releaser workflow
  .github/workflows/releaser.yml
Labels: chore

#264 🐎 RLE for memory in snapshots
  src/Debug/debugger.cpp
Labels: performance
