Repository TOPLLab/WARDuino, pull requests merged in 2024-09, with the labels that each got.

#259 Fix benchmark compilation
  benchmarks/makefile
Labels: chore

#262 ⬆️ Update to latch ` 0.3.0`
  tests/latch/latch-0.2.1.tgz
  tests/latch/latch-0.3.0.tgz
  tests/latch/package-lock.json
  tests/latch/package.json
  tests/latch/src/spec.test.ts
Labels: tests

#250 Reversible primitives
  platforms/Zephyr/boards/stm32l496g_disco.overlay
  src/Debug/debugger.cpp
  src/Debug/debugger.h
  src/Primitives/arduino.cpp
  src/Primitives/emulated.cpp
  src/Primitives/idf.cpp
  src/Primitives/primitives.h
  src/Primitives/zephyr.cpp
  src/WARDuino.h
Labels: major feature
