Repository TOPLLab/WARDuino, pull requests merged in 2024-04, with the labels that each got.

#236 Add async snapshot interrupt
  src/Debug/debugger.cpp
  src/Debug/debugger.h
  src/Interpreter/instructions.cpp
  src/Interpreter/interpreter.cpp
Labels: feature

#242 Fix arduino compilation
  README.md
  tutorials/.gitignore
  tutorials/README.md
  tutorials/assemblyscript/.gitignore
  tutorials/assemblyscript/CMakeLists.txt
  tutorials/assemblyscript/README.md
  tutorials/assemblyscript/as-warduino-0.1.1.tgz
  tutorials/assemblyscript/asconfig.json
  tutorials/assemblyscript/main/CMakeLists.txt
  tutorials/assemblyscript/main/analog-io.ts
  tutorials/assemblyscript/main/analog.ts
  tutorials/assemblyscript/main/ascii.ts
  tutorials/assemblyscript/main/blink-without-delay.ts
  tutorials/assemblyscript/main/blink.ts
  tutorials/assemblyscript/main/button.ts
  tutorials/assemblyscript/main/config.ts
  tutorials/assemblyscript/main/configuration.ts
  tutorials/assemblyscript/main/main.cpp
  tutorials/assemblyscript/main/smartlamp.ts
  tutorials/assemblyscript/main/wifi.ts
  tutorials/assemblyscript/package-lock.json
  tutorials/assemblyscript/package.json
  tutorials/rust/.gitignore
  tutorials/rust/README.md
  tutorials/rust/build.sh
  tutorials/rust/examples/analog-io/.cargo/config
  tutorials/rust/examples/analog-io/Cargo.toml
  tutorials/rust/examples/analog-io/button.wat
  tutorials/rust/examples/analog-io/main/main.rs
  tutorials/rust/examples/analog/.cargo/config
  tutorials/rust/examples/analog/Cargo.toml
  tutorials/rust/examples/analog/button.wat
  tutorials/rust/examples/analog/main/main.rs
  tutorials/rust/examples/ascii/.cargo/config
  tutorials/rust/examples/ascii/Cargo.toml
  tutorials/rust/examples/ascii/main/main.rs
  tutorials/rust/examples/button/.cargo/config
  tutorials/rust/examples/button/Cargo.toml
  tutorials/rust/examples/button/button.wat
  tutorials/rust/examples/button/main/main.rs
  tutorials/rust/examples/configuration/.cargo/config
  tutorials/rust/examples/configuration/Cargo.toml
  tutorials/rust/examples/configuration/button.wat
  tutorials/rust/examples/configuration/main/config.rs
  tutorials/rust/examples/configuration/main/main.rs
  tutorials/rust/lib/warduino/.gitignore
  tutorials/rust/lib/warduino/Cargo.toml
  tutorials/rust/lib/warduino/src/lib.rs
  tutorials/rust/lib/warduino/src/linking.rs
  tutorials/wat/CMakeLists.txt
  tutorials/wat/README.md
  tutorials/wat/build.sh
  tutorials/wat/main/CMakeLists.txt
  tutorials/wat/main/blink.wat
  tutorials/wat/main/fac.wat
  tutorials/wat/main/main.cpp
Labels: bug

#241 Port WARDuino to the Zephyr RTOS
  CMakeLists.txt
  platforms/ESP-IDF/CMakeLists.txt
  platforms/Zephyr/.gitignore
  platforms/Zephyr/CMakeLists.txt
  platforms/Zephyr/Kconfig
  platforms/Zephyr/app.overlay
  platforms/Zephyr/boards/rpi_pico.overlay
  platforms/Zephyr/boards/stm32l496g_disco.overlay
  platforms/Zephyr/main.cpp
  platforms/Zephyr/prj.conf
  src/Debug/debugger.cpp
  src/Debug/debugger.h
  src/Edward/proxy_supervisor.cpp
  src/Edward/proxy_supervisor.h
  src/Interpreter/instructions.cpp
  src/Interpreter/interpreter.cpp
  src/Primitives/zephyr.cpp
  src/Threading/warduino-thread.h
  src/Utils/sockets.cpp
Labels: major feature
